In [9]:
import pandas as pd
from PyQt5.QtCore import QDate
from nltk import NaiveBayesClassifier

df_fake = pd.read_csv('data/Fake.csv')
df_true = pd.read_csv('data/True.csv')

'WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support educat

In [10]:
df_fake["label"] = 1  # Fake news
df_true["label"] = 0  # True news

In [56]:
df_combined = pd.concat([df_fake, df_true], axis=0)
df_combined

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text    subject  \
0      Donald Trump just couldn t wish all Americans ...       News   
1      House Intelligence Committee Chairman Devin Nu...       News   
2      On Friday, it was revealed that former Milwauk...       News   
3      On Christmas day, Donald Trump announced that ...       News   
4      Pope Francis used his annual Christmas Day mes...       News   
...                                                  ...        ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...  worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...  worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...  worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...  worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...  worldnews   

                    date  label  
0      December 31, 2017      1  
1      December 31, 2017      1  
2      December 30, 2017      1  
3      December 29, 2017      1  
4      December 25, 2017      1  
...                  ...    ...  
21412   August 22, 2017       0  
21413   August 22, 2017       0  
21414   August 22, 2017       0  
21415   August 22, 2017       0  
21416   August 22, 2017       0  

[44898 rows x 5 columns]

In [57]:
df_combined = df_combined.sample(frac=1, random_state=42).reset_index(drop=True)

In [58]:
df_combined

title  \
0      Ben Stein Calls Out 9th Circuit Court: Committ...   
1      Trump drops Steve Bannon from National Securit...   
2      Puerto Rico expects U.S. to lift Jones Act shi...   
3       OOPS: Trump Just Accidentally Confirmed He Le...   
4      Donald Trump heads for Scotland to reopen a go...   
...                                                  ...   
44893  UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...   
44894  PM May seeks to ease Japan's Brexit fears duri...   
44895  Merkel: Difficult German coalition talks can r...   
44896   Trump Stole An Idea From North Korean Propaga...   
44897  BREAKING: HILLARY CLINTON’S STATE DEPARTMENT G...   

                                                    text       subject  \
0      21st Century Wire says Ben Stein, reputable pr...       US_News   
1      WASHINGTON (Reuters) - U.S. President Donald T...  politicsNews   
2      (Reuters) - Puerto Rico Governor Ricardo Rosse...  politicsNews   
3      On Monday, Donald Trump once again embarrassed...          News   
4      GLASGOW, Scotland (Reuters) - Most U.S. presid...  politicsNews   
...                                                  ...           ...   
44893                                                         politics   
44894  LONDON/TOKYO (Reuters) - British Prime Ministe...     worldnews   
44895  BERLIN (Reuters) - Chancellor Angela Merkel sa...     worldnews   
44896  Jesus f*cking Christ our President* is a moron...          News   
44897  IF SHE S NOT TOAST NOW THEN WE RE IN BIGGER TR...      politics   

                      date  label  
0        February 13, 2017      1  
1           April 5, 2017       0  
2      September 27, 2017       0  
3             May 22, 2017      1  
4           June 24, 2016       0  
...                    ...    ...  
44893         Mar 27, 2017      1  
44894     August 29, 2017       0  
44895   November 16, 2017       0  
44896        July 14, 2017      1  
44897         Apr 23, 2015      1  

[44898 rows x 5 columns]

In [59]:
df_combined.to_csv("data/full_fake_news_dataset.csv", index=False)

In [60]:
df = pd.read_csv("data/full_fake_news_dataset.csv")
df.head()

title  \
0  Ben Stein Calls Out 9th Circuit Court: Committ...   
1  Trump drops Steve Bannon from National Securit...   
2  Puerto Rico expects U.S. to lift Jones Act shi...   
3   OOPS: Trump Just Accidentally Confirmed He Le...   
4  Donald Trump heads for Scotland to reopen a go...   

                                                text       subject  \
0  21st Century Wire says Ben Stein, reputable pr...       US_News   
1  WASHINGTON (Reuters) - U.S. President Donald T...  politicsNews   
2  (Reuters) - Puerto Rico Governor Ricardo Rosse...  politicsNews   
3  On Monday, Donald Trump once again embarrassed...          News   
4  GLASGOW, Scotland (Reuters) - Most U.S. presid...  politicsNews   

                  date  label  
0    February 13, 2017      1  
1       April 5, 2017       0  
2  September 27, 2017       0  
3         May 22, 2017      1  
4       June 24, 2016       0

In [61]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")
stop_words = set(stopwords.words("english"))

def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers
    text = re.sub(r'\W', ' ', text)
    # Remove stopwords
    text = " ".join(word for word in text.split() if word not in stop_words)
    return text

# Apply preprocessing
df["clean_text"] = df["text"].apply(preprocess_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/youssefmalek/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [62]:
df.head()

title  \
0  Ben Stein Calls Out 9th Circuit Court: Committ...   
1  Trump drops Steve Bannon from National Securit...   
2  Puerto Rico expects U.S. to lift Jones Act shi...   
3   OOPS: Trump Just Accidentally Confirmed He Le...   
4  Donald Trump heads for Scotland to reopen a go...   

                                                text       subject  \
0  21st Century Wire says Ben Stein, reputable pr...       US_News   
1  WASHINGTON (Reuters) - U.S. President Donald T...  politicsNews   
2  (Reuters) - Puerto Rico Governor Ricardo Rosse...  politicsNews   
3  On Monday, Donald Trump once again embarrassed...          News   
4  GLASGOW, Scotland (Reuters) - Most U.S. presid...  politicsNews   

                  date  label  \
0    February 13, 2017      1   
1       April 5, 2017       0   
2  September 27, 2017       0   
3         May 22, 2017      1   
4       June 24, 2016       0   

                                          clean_text  
0  21st century wire says ben stein reputable pro...  
1  washington reuters u president donald trump re...  
2  reuters puerto rico governor ricardo rossello ...  
3  monday donald trump embarrassed country accide...  
4  glasgow scotland reuters u presidential candid...

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=2500)  # Limit to top 5000 words

# Transform the text data
X_tfidf = tfidf_vectorizer.fit_transform(df["clean_text"])

# Convert to DataFrame for visualization
tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

tfidf_df.head()

000   10  100   11   12       13   14   15   16        17  ...  years  \
0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.000000  ...    0.0   
1  0.0  0.0  0.0  0.0  0.0  0.03221  0.0  0.0  0.0  0.032723  ...    0.0   
2  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.000000  ...    0.0   
3  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.000000  ...    0.0   
4  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.000000  ...    0.0   

   yemen  yes  yesterday      yet  york     young  youtube  zero  zone  
0    0.0  0.0        0.0  0.00000   0.0  0.000000      0.0   0.0   0.0  
1    0.0  0.0        0.0  0.00000   0.0  0.029893      0.0   0.0   0.0  
2    0.0  0.0        0.0  0.00000   0.0  0.000000      0.0   0.0   0.0  
3    0.0  0.0        0.0  0.00000   0.0  0.000000      0.0   0.0   0.0  
4    0.0  0.0        0.0  0.04996   0.0  0.000000      0.0   0.0   0.0  

[5 rows x 2500 columns]

In [74]:
from sklearn.model_selection import train_test_split

# Define features (X) and labels (y)
X = X_tfidf  # TF-IDF transformed text
y = df["label"]  # Fake (0) or Real (1)

# Split dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [75]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Train the model
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

# Predictions
y_pred = nb_model.predict(X_test)

# Evaluate Performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

# Show classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Show confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Model Accuracy: 0.9262

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.92      0.92      4270
           1       0.93      0.93      0.93      4710

    accuracy                           0.93      8980
   macro avg       0.93      0.93      0.93      8980
weighted avg       0.93      0.93      0.93      8980


Confusion Matrix:
 [[3922  348]
 [ 315 4395]]


In [104]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA, QuadraticDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer


In [105]:
from sklearn.linear_model import LogisticRegression

pipeline_pca = Pipeline([
    ("pca", PCA(n_components=100)),  # Reduce to 100 dimensions
    ("lr", LogisticRegression())  # Use logistic regression instead of NB
])

pipeline_lda = Pipeline([
    ("lda", LDA(n_components=1)),  # LDA reduces to 1D
    ("lr", LogisticRegression())  # Logistic regression works better
])



In [106]:
# Train PCA + Logistic Regression
pipeline_pca.fit(X_train, y_train)
y_pred_pca = pipeline_pca.predict(X_test.toarray())

# Train LDA + Logistic Regression
pipeline_lda.fit(X_train.toarray(), y_train)
y_pred_lda = pipeline_lda.predict(X_test.toarray())

# Evaluate Performance
print("📌 PCA + Logistic Regression Results")
print(f"Accuracy: {accuracy_score(y_test, y_pred_pca):.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_pca))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_pca))

print("\n📌 LDA + Logistic Regression Results")
print(f"Accuracy: {accuracy_score(y_test, y_pred_lda):.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_lda))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lda))


📌 PCA + Logistic Regression Results
Accuracy: 0.9654
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96      4270
           1       0.97      0.96      0.97      4710

    accuracy                           0.97      8980
   macro avg       0.97      0.97      0.97      8980
weighted avg       0.97      0.97      0.97      8980

Confusion Matrix:
 [[4138  132]
 [ 179 4531]]

📌 LDA + Logistic Regression Results
Accuracy: 0.9888
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      4270
           1       0.99      0.99      0.99      4710

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

Confusion Matrix:
 [[4217   53]
 [  48 4662]]


In [107]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.stats import uniform, loguniform
from sklearn.svm import LinearSVC


In [108]:
# XGBoost hyperparameters
xgb_param_dist = {
    "xgb__n_estimators": np.arange(50, 300, 50),  # Number of trees
    "xgb__max_depth": np.arange(3, 12, 2),  # Tree depth
    "xgb__learning_rate": loguniform(0.001, 0.3),  # Learning rate
    "xgb__subsample": uniform(0.5, 0.5),  # Random subset of data
    "xgb__colsample_bytree": uniform(0.5, 0.5),  # Random subset of features
}

# Kernel SVM hyperparameters
svm_param_dist = {
    "svm__C": loguniform(0.01, 100),  # Regularization parameter
    "svm__gamma": loguniform(0.001, 1),  # Kernel coefficient
    "svm__kernel": ["rbf", "poly", "sigmoid"],  # Different kernels
}


In [109]:
pipeline_xgb_pca = Pipeline([
    ("pca", PCA(n_components=20)),  # PCA reduces to 100 dimensions
    ("xgb", XGBClassifier(use_label_encoder=False, eval_metric="logloss"))
])


In [110]:
pipeline_xgb = Pipeline([
    ("xgb", XGBClassifier(use_label_encoder=False, eval_metric="logloss"))
])


In [111]:
pipeline_svm_pca = Pipeline([
    ("pca", PCA(n_components=20)),  # PCA reduces to 100 dimensions
    ("svm", LinearSVC())  # Linear SVM
])


In [112]:
pipeline_svm = Pipeline([
    ("svm", SVC(probability=True))  # Kernel SVM
])

In [100]:
from sklearn.model_selection import StratifiedKFold

# Use Stratified K-Fold for better evaluation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# RandomizedSearch for XGBoost + PCA
search_xgb_pca = RandomizedSearchCV(pipeline_xgb_pca, param_distributions=xgb_param_dist,
                                    n_iter=5, cv=cv, scoring="accuracy", random_state=42, n_jobs=-1)
search_xgb_pca.fit(X_train, y_train)

# # RandomizedSearch for XGBoost without PCA
# search_xgb = RandomizedSearchCV(pipeline_xgb, param_distributions=xgb_param_dist,
#                                 n_iter=5, cv=cv, scoring="accuracy", random_state=42, n_jobs=-1)
# search_xgb.fit(X_train, y_train)
# 
# 
# # RandomizedSearch for Kernel SVM without PCA
# search_svm = RandomizedSearchCV(pipeline_svm, param_distributions=svm_param_dist,
#                                 n_iter=5, cv=cv, scoring="accuracy", random_state=42, n_jobs=-1)
# search_svm.fit(X_train, y_train)


python(2493) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2494) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2495) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2496) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2497) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2498) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2499) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2500) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2501) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2502) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(2503) MallocStackLoggin

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=Pipeline(steps=[('pca', PCA(n_components=20)),
                                             ('xgb',
                                              XGBClassifier(base_score=None,
                                                            booster=None,
                                                            callbacks=None,
                                                            colsample_bylevel=None,
                                                            colsample_bynode=None,
                                                            colsample_bytree=None,
                                                            device=None,
                                                            early_stopping_rounds=None,
                                                            enable_categorical=False,
                                                            eval_metric='logloss...
                   param_distributions={'xgb__colsample_bytree': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x30b06de80>,
                                        'xgb__learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x30b06f350>,
                                        'xgb__max_depth': array([ 3,  5,  7,  9, 11]),
                                        'xgb__n_estimators': array([ 50, 100, 150, 200, 250]),
                                        'xgb__subsample': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x30b06f7a0>},
                   random_state=42, scoring='accuracy')

In [101]:
# Helper function to evaluate models
def evaluate_model(model, X_test, y_test, name):
    y_pred = model.predict(X_test.toarray())
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\n📌 {name} Results")
    print(f"Best Accuracy: {accuracy:.4f}")
    print("Best Parameters:", model.best_params_)
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Evaluate models
evaluate_model(search_xgb_pca, X_test, y_test, "XGBoost + PCA")
# evaluate_model(search_xgb, X_test, y_test, "XGBoost without PCA")
# evaluate_model(search_svm_pca, X_test, y_test, "Kernel SVM + PCA")
# evaluate_model(search_svm, X_test, y_test, "Kernel SVM without PCA")



📌 XGBoost + PCA Results
Best Accuracy: 0.9699
Best Parameters: {'xgb__colsample_bytree': 0.6872700594236812, 'xgb__learning_rate': 0.22648248189516848, 'xgb__max_depth': 7, 'xgb__n_estimators': 250, 'xgb__subsample': 0.7984250789732434}
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.96      0.97      4270
           1       0.97      0.98      0.97      4710

    accuracy                           0.97      8980
   macro avg       0.97      0.97      0.97      8980
weighted avg       0.97      0.97      0.97      8980

Confusion Matrix:
 [[4112  158]
 [ 112 4598]]


In [102]:
# Train PCA + SVM
pipeline_svm_pca.fit(X_train, y_train)
y_pred_svm_pca = pipeline_svm_pca.predict(X_test.toarray())
evaluate_model(pipeline_svm_pca, X_test, y_test, "SVM + PCA")


📌 SVM + PCA Results
Best Accuracy: 0.9488


AttributeError: 'Pipeline' object has no attribute 'best_params_'

In [130]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from nltk.classify import naivebayes
pipeline_qda = Pipeline([
    ("pca", PCA(n_components=100)), 
    ("qda", naivebayes())
])

TypeError: 'module' object is not callable

In [126]:
pipeline_qda.fit(X_train, y_train)

Pipeline(steps=[('pca', PCA(n_components=100)),
                ('qda', LinearDiscriminantAnalysis(n_components=1))])

In [127]:
y_pred_qda = pipeline_qda.predict(X_test.toarray())

In [128]:
print("\n📌 PCA + QDA Results")
print(f"Accuracy: {accuracy_score(y_test, y_pred_qda):.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_qda))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_qda))



📌 PCA + QDA Results
Accuracy: 0.9624
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96      4270
           1       0.97      0.95      0.96      4710

    accuracy                           0.96      8980
   macro avg       0.96      0.96      0.96      8980
weighted avg       0.96      0.96      0.96      8980

Confusion Matrix:
 [[4144  126]
 [ 212 4498]]
